enabled_layouts *
font_size 14.0
font_family      family='JetBrains Mono' style=Light variable_name=JetBrainsMono
bold_font        family='JetBrains Mono' style=Regular variable_name=JetBrainsMono
italic_font      auto
bold_italic_font family='JetBrains Mono' style=Medium variable_name=JetBrainsMonoItalic
include current-theme.conf
disable_ligatures cursor
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+f show_scrollback
map cmd+d launch --cwd=current --location=vsplit
map cmd+shift+d launch --cwd=current --location=hsplit
map cmd+t launch --type=tab --cwd=current
map cmd+n launch --type=os-window --cwd=current
map cmd+w close_window
map ctrl+j next_window
map ctrl+k previous_window
map ctrl+l next_tab
map ctrl+h previous_tab
map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down
map ctrl+shift+left resize_window narrower
map ctrl+shift+right resize_window wider
map ctrl+shift+up resize_window shorter
map ctrl+shift+down resize_window taller
map ctrl+shift+0 resize_window reset
map cmd+g combine : clear_terminal scrollback active : send_text normal,application \x0c
map shift+enter combine : clear_terminal scrollback active : send_text normal,application \x0c : sleep 0.1 : send_text normal,application \x0d
map ctrl+shift+l next_layout
map ctrl+s toggle_layout stack
map ctrl+t goto_layout tall:bias=50;full_size=1;mirrored=false
